### ISSUE TITLE
支持扫码登录其他设备

### ISSUE THREAD

**Issue by mokurin000** [orz12/PiliPalaX#114]
### 功能描述
支持打开相机扫描二维码登录其他设备

### 目标
如用于授权各种B站二维码登录

### 解决方案
zxing 解码二维码

### 其他
可能需要参考 现成逆向的grpc接口

**Comment by xsfx0313** [comment]
你这个太不现实了，提供扫码借口是b站**绝对**不允许的，这也对b站很不安全，你是想让开发者犯非法侵入计算机系统罪吗？建议开发者直接close

**Comment by orz12** [comment]
目前只提供被扫码的功能
