### ISSUE TITLE
投币功能改进

### ISSUE THREAD

**Issue by MarvelousTune** [orz12/PiliPalaX#120]
### 功能描述
快速视频投币

### 目标
减少操作次数

### 解决方案
照抄一下官方样式 或者加设置选项默认选定投几个币

**Comment by orz12** [comment]
按钮改成投1枚/投2枚，直接点击就投出去？

**Comment by MarvelousTune** [comment]
> 按钮改成投1枚/投2枚，直接点击就投出去？

对的

**Comment by orz12** [comment]
已经改了

**Comment by VillagerTom** [comment]
官方就是手动选择投币数啊
