### ISSUE TITLE
无法使用app推荐流

### ISSUE THREAD

**Issue by Alpha-Qian** [orz12/PiliPalaX#122]
![Screenshot_2024-07-10-21-28-38-089_com orz12 PiliPalaX](https://github.com/orz12/pilipala/assets/154665575/f19cb2a0-f9c7-4707-96ff-0e7447a0e28e)

其他页面正常，重新登陆可以临时解决，但隔不就又会重新出现

问题发生前出现了这个错误，后继刷新没有报错
PiliPalaX错误日志
********************
------- 设备信息 -------
id: TKQ1.221013.002
board: sunstone
bootloader: unknown
brand: Redmi
device: sunstone
display: TKQ1.221013.002 test-keys
fingerprint: Redmi/sunstone/sunstone:13/TKQ1.221013.002/V14.0.10.0.TMQCNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-224429-v645b-0s9gt-nkwjs
isPhysicalDevice: true
manufacturer: Xiaomi
model: 22101317C
product: sunstone
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.10.0.TMQCNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-12-01
------- 应用信息 -------
environment: release
version: 1.0.22
appName: PiliPalaX
buildNumber: 1623
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
ClientException: Software caused connection abort, uri=http://i0.hdslb.com/bfs/archive/9ecc0e31040b35e255468c62b2fc4f741fec7d38.jpg@10q.webp
------- 错误堆栈 -------
------- CUSTOM INFO -------

**Comment by Alpha-Qian** [comment]
重新用短信登陆后问题解决，或许是一开始用扫码登录导致的（？）或许应该在扫码登录界面提示？

**Comment by Alpha-Qian** [comment]
不知道为什么扫码登的又好了，我关了

**Comment by orz12** [comment]
给app推荐接口新增了更多的参数，可以在新版试一下效果

**Comment by Alpha-Qian** [comment]
什么意思？这就是最新版啊

**Comment by orz12** [comment]
> 什么意思？这就是最新版啊

我回复的时候又推了一版上来

**Comment by VillagerTom** [comment]
最新版是否正常？

**Comment by Alpha-Qian** [comment]
正常
