### ISSUE TITLE
平板开启横屏适配后，在视频合集播放页面中无法切换集数

### ISSUE THREAD

**Issue by AndyHYN** [orz12/PiliPalaX#124]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by orz12** [comment]
没太理解，可以发个录屏吗？

**Comment by AndyHYN** [comment]
> 没太理解，可以发个录屏吗？

https://github.com/user-attachments/assets/7b982416-63c7-47ea-8ced-38b9dcb9893d

不知道为什么用小窗就可以，感谢大佬🍺

**Comment by pigyee** [comment]
同问

**Comment by orz12** [comment]
查出来了，是没有处理默认显示评论区选项导致的。新版已经修好
