### ISSUE TITLE
界面、综合反馈

### ISSUE THREAD

**Issue by YiDuoCiMei** [orz12/PiliPalaX#128]
![Screenshot_20240712_054003](https://github.com/user-attachments/assets/5c79db57-5eaa-4921-bac5-76c80e4b6fd2)
![Screenshot_20240712_054008](https://github.com/user-attachments/assets/8c053c7b-266e-4e0f-934e-2f59ee0ff47f)
![Screenshot_20240712_054055](https://github.com/user-attachments/assets/a22a9c2f-f2b9-4b35-af26-79aceaeaba52)
![Screenshot_20240712_054827](https://github.com/user-attachments/assets/edfe3673-65fd-46dc-b2ac-401260593ded)
![Screenshot_20240712_055744](https://github.com/user-attachments/assets/f3da0830-6327-41fe-a149-6f04ad6c170b)
![Screenshot_20240712_060702](https://github.com/user-attachments/assets/a7f661e0-f101-4925-a1a8-e2f3c40b37bf)
![Screenshot_20240712_060715](https://github.com/user-attachments/assets/99ecacfb-7f42-4c55-83fb-5d857a1eb1d7)
![Screenshot_20240712_060801](https://github.com/user-attachments/assets/9bed6de3-0c8b-4648-aaba-11a61d2a872c)
![Screenshot_20240712_061050](https://github.com/user-attachments/assets/9f0245a6-c895-469c-8539-d2b60c679c37)
![Screenshot_20240712_062243](https://github.com/user-attachments/assets/52d16955-19a9-46f2-bdc1-40c5b7d3183d)
![Screenshot_20240712_084409](https://github.com/user-attachments/assets/93a1cd89-7d5e-4b51-a539-8b7bc32b19be)
![Screenshot_20240712_103828](https://github.com/user-attachments/assets/af597fbc-7bff-43b1-ac19-f41f626e6d2b)
![Screenshot_20240712_143524](https://github.com/user-attachments/assets/6c99ec9b-d641-44b7-84bc-8f2baddcefd3)
![Screenshot_20240712_143545](https://github.com/user-attachments/assets/3a5141b8-b5b5-4ad3-a9ef-2475178f6ff8)
![Screenshot_20240713_112340](https://github.com/user-attachments/assets/a5254649-392d-4d1e-8235-060d20c4631f)

**Comment by YiDuoCiMei** [comment]
1，视频加载问题，
现在很大概率出现黑屏、白屏，
黑屏在人工切换一个视频编码就能正常播放，

白屏则需要播放另一个视频才有概率解决，
或者等待很长时间也能可能加载成功，

2，播放过程种偶尔会出现音频报错，
现在的提升气泡太小了，位置太低，
很难注意和看得清，

3，多多个界面卡片样式不同，
有的页面是三列，有的四列，有的五列，
建议不同界面信息流统一成1~2种，

4，这次更新后播放器的合集上面点击切换视频，
现在切换不了了

5，这次关系的手势，上下滑动切换全屏，
没有以前灵活了，不好处罚，也容易识别成调节音量、亮度，

6，其余是基界面加载和布局优化

**Comment by orz12** [comment]
你给得建议好详细，非常感谢，一定是深度用户吧！有没有兴趣参与pull request？
你提到了第1和5进行了回退，4我这里复现不了，你可以看看是不是也修复了。
你提到的2中的气泡提示位置，以及众多界面大小、列表项未适配、列数不同、加载项不全，受限于我自己仅使用手机版，很多问题都是借助用户的反馈得知的并逐步修改的。
另外，很多布局制作多个尺寸兼容相对较难，例如“我的”弹窗，之前有一版比这个大，但小屏机的显示就溢出了，就暂时改成了这个比较“憋屈”的样子，后续可能会以屏幕宽度计算尺寸的方式实现。
对于加载项不全这个问题，由于平板的尺寸就是大于手机（比如手机可能显示6～8条就满了，平板需要显示20～40条），但很多接口请求的数量有限，且原有的适配翻页加载设计就不适合这种数据显示不满的情况（因为翻不动，触发不了滚动条监听事件）。我目前的临时解决方式是能修改单次请求条数的就修改，修改不了的就延时后多加载一页，但我不确定有没有更好的思路去应对这类情况，如果有好想法欢迎提出！
其它一些回应：
投稿加载不出来/默认显示投稿（或收藏等），b站在投稿查询接口上加了很多针对爬虫的风控限制，相对较容易触发。后续可能会视实现难度替换成app端接口或者跟随风控策略更新。在接口相对稳定的情况下再上默认显示。收藏功能也已有反馈，受限于精力和时间暂时还没有开始制作。
视频加载不出来：在准备CDN的自定义设置，会在近期上线，对该情况有一定的缓解作用。此外可能会进一步下调默认的视频缓冲大小，缩短黑屏等待时间。
播放页横屏适配下方很空：暂时不考虑播放器下移并上下留黑边的方案，可能会在后续修改视频简介组件，例如额外显示视频说明、视频标签、联合投稿等，帮助充实页面内容。但这个优先级较低，也欢迎提出pr。

**Comment by orz12** [comment]
另外 也欢迎您加入设置-关于页面的QQ群一起交流想法。一下子太多的内容肯定做不出来，需要大家一起完善。

**Comment by VillagerTom** [comment]
看截图，你是群里的hydrogen？

**Comment by YiDuoCiMei** [comment]
> 看截图，你是群里的hydrogen吗？

是的

**Comment by YiDuoCiMei** [comment]
> 你给得建议好详细，非常感谢，一定是深度用户吧！有没有兴趣参与pull request？
> 你提到了第1和5进行了回退，4我这里复现不了，你可以看看是不是也修复了。
> 你提到的2中的气泡提示位置，以及众多界面大小、列表项未适配、列数不同、加载项不全，受限于我自己仅使用手机版，很多问题都是借助用户的反馈得知的并逐步修改的。
> 另外，很多布局制作多个尺寸兼容相对较难，例如“我的”弹窗，之前有一版比这个大，但小屏机的显示就溢出了，就暂时改成了这个比较“憋屈”的样子，后续可能会以屏幕宽度计算尺寸的方式实现。
> 对于加载项不全这个问题，由于平板的尺寸就是大于手机（比如手机可能显示6～8条就满了，平板需要显示20～40条），但很多接口请求的数量有限，且原有的适配翻页加载设计就不适合这种数据显示不满的情况（因为翻不动，触发不了滚动条监听事件）。我目前的临时解决方式是能修改单次请求条数的就修改，修改不了的就延时后多加载一页，但我不确定有没有更好的思路去应对这类情况，如果有好想法欢迎提出！
> 其它一些回应：
> 投稿加载不出来/默认显示投稿（或收藏等），b站在投稿查询接口上加了很多针对爬虫的风控限制，相对较容易触发。后续可能会视实现难度替换成app端接口或者跟随风控策略更新。在接口相对稳定的情况下再上默认显示。收藏功能也已有反馈，受限于精力和时间暂时还没有开始制作。
> 视频加载不出来：在准备CDN的自定义设置，会在近期上线，对该情况有一定的缓解作用。此外可能会进一步下调默认的视频缓冲大小，缩短黑屏等待时间。
> 播放页横屏适配下方很空：暂时不考虑播放器下移并上下留黑边的方案，可能会在后续修改视频简介组件，例如额外显示视频说明、视频标签、联合投稿等，帮助充实页面内容。但这个优先级较低，也欢迎提出pr。

1，个人觉得播放是重要的，其他问题都是界面问题，没有那么重要，播放是核心功能，
黑屏、白屏、中途音频错误，我的想法是优化重试，
白屏现在是花时间等待，而黑屏时的重试没什么效果，
每次手动切换视频编码就能播放，这个问题值得解决，
2，手势在昨天更新后没有改善，
可触发的面积减小了，也不灵敏，
3，不能切视频，
另一个别人的议题里也有，横屏进去播放界面后就不可能，
竖屏进入播放是可以切换的，
因此手机可能不会出现，
4，气泡窗口，我观察了手机和平板面积是差不多的，
建议手机和平板做成固定两个大小，
识别是平板的时，横屏、竖屏提供大的弹窗和气泡，
5，加载问题根据实际情况再说吧，
虽然提到很多，现在还有问题的也并不是常用的界面，
而新界面和功能再有了规划后再说，

**Comment by YiDuoCiMei** [comment]
> 另外 也欢迎您加入设置-关于页面的QQ群一起交流想法。一下子太多的内容肯定做不出来，需要大家一起完善。

补充一下，
前两天我发现一个APP，可以缓存视频，
我才反应过来，骁龙8G2以前的CPU不支持硬件AV1，
而我是8G1和865，都不支持硬解AV1，

而我之前觉得AV1高级一些，HEVC兼容性不好，
所以都是设置的AV1和AVC，

现在我才发现不能硬解，然后把设置改成HEVC和AVC，
测试了很多视频的，几乎都能打开，基本全部都可以，

黑屏时间非常短，有重试也很快，加载4K比原先1080P还快，
出现白屏的等待时间也很短，黑屏、白屏加载都很快，几乎不用等待，成功率高，

我缓存了视频对比AV1和HEVC的码率应该接近的，文件大小差不多，
而AVC文件比较大，差距好几倍，

所以我猜是因为不能硬解AV1和AVC码率两个原因加起来导致有的视频会加载不成功或者比较慢，
而之前显示重试的时候，人工切换编码马上就能播放，也可能有关系，AV1和AVC相互切都有过，
所以我也怀疑重试的时候编码是不是没有实际切换过来，才需要手动切，

这是我不严谨的对比，也不一定保证对，给使用习惯一种参考，
