### ISSUE TITLE
[BUG] 首页推荐同时长按多个视频会导致封面大图无法关闭

### ISSUE THREAD

**Issue by ajdgsu** [orz12/PiliPalaX#132]
### 问题描述
当在首页同时长按两个或两个以上的视频时，会同时出现多个视频封面的大图，但是只能关闭掉第一个封面，剩下的封面无论如何都无法关闭，只能强制重开软件才能复原。

### 复现步骤
进入首页推荐
用多根手指同时长按多个视频窗口
尝试关闭弹出的封面图像

### 预期行为
全部正常关闭

### 错误日志
小米 13 MIUI 14.0.17
1.0.22-beta.3+165

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by orz12** [comment]
修了，感谢[bggRGjQaUbCoE](https://github.com/bggRGjQaUbCoE)
