### ISSUE TITLE
多指滑动时会导致滑动速度等倍增加

### ISSUE THREAD

**Issue by ajdgsu** [orz12/PiliPalaX#133]
### 问题描述
当使用单根手指滑动界面时一切正常，但是如果使用两根手指滑动时滑动速度会变成两倍，用五根手指滑动会时滑动速度会变成五倍，以此类推。

(虽说这个奇怪的特性挺酷的，但还是修掉比较好)

### 复现步骤
任意界面使用两根或以上的手指滑动界面

### 预期行为
正常工作

### 错误日志
小米 13 MIUI 14.0.17
1.0.22-beta.1+163

**Comment by orz12** [comment]
手势换了一种实现方式

**Comment by ajdgsu** [comment]
> 手势换了一种实现方式

明白，不过我说的是在软件的任意区域进行滑动，和手势无关。举个例子，在视频评论区内使用双指滑动评论，评论滑动速度会变成两倍，同理用五根手指就会变成五倍。

**Comment by orz12** [comment]
太酷了 我第一次发现
https://juejin.cn/post/7320135997354573876
看起来很像是这个引起的
我目前不太懂怎么修（其实也可以不用修？）

**Comment by VillagerTom** [comment]
更新了Flutter版本至3.24.0，bug是否被修复？（几个月前我就听tg群友说新版Flutter修复了多指交互倍速的bug）

**Comment by ajdgsu** [comment]
确实，新版的已经没有问题了
