### ISSUE TITLE
BUG: 合集中切换视频时标题和简介不会更新

### ISSUE THREAD

**Issue by lingbopro** [orz12/PiliPalaX#138]
### 问题描述
如题

### 复现步骤
打开一个合集中的视频，并切换到另一个此合集中的视频，视频标题和简介不会更新，还是之前的那个视频，全屏模式也可复现

### 预期行为
视频标题和简介应更新为新的视频的标题和简介

### 错误日志
APP: `1.0.22-beta.4+166`  
系统: `HarmonyOS 3 (Android 10)`  
设备: `HUAWEI Mate 20 Pro`  

### 相关信息

https://github.com/user-attachments/assets/c119c48c-cd4d-456b-9050-9d5a2f5915fa

**Comment by orz12** [comment]
改了

**Comment by lingbopro** [comment]
但是全屏界面上方的标题还是没变啊

**Comment by lingbopro** [comment]
> 但是全屏界面上方的标题还是没变啊

哼哼哼啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by lingbopro** [comment]
@orz12 @VillagerTom 横屏模式下切换合集分集顶部标题依然不会改变啊

**Comment by Gitkila** [comment]
@orz12 现在合集里面的分集和分p标题和简介可以更新，但是封面不能更新，而且如果一开始点进视频时没点击播放，从列表切换视频则会播放最开始进入的视频，需要再次点击目录里面的分集或分p才能播放目标视频，希望作者可以修复一下，谢谢。
