### ISSUE TITLE
拉黑了up主后还能再推荐中看到，好像拉黑没有用😅

### ISSUE THREAD

**Issue by AndyHYN** [orz12/PiliPalaX#139]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by xsfx0313** [comment]
这可能是b站官方推荐系统的问题，您确认b站官方客户端也有此问题吗，我们需要确认此问题是由谁产生的，谢谢😆
