### ISSUE TITLE
连续刷视频时，有较大概率视频会没有声音。 使用时间稍微久一点发热就比较严重。

### ISSUE THREAD

**Issue by lingwu66** [orz12/PiliPalaX#141]
### 问题描述
请提供一个清晰而简明的问题描述。
### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by xsfx0313** [comment]
请描述你的详细问题，软件版本，手机系统和型号。

发热问题过于模糊，无法定位此问题原因。

关于视频没有声音，请描述你在什么情况下，你做了什么，软件正在做什么，请详细描述，并给出你的复现步骤。

为解决这些问题，请补充这些信息，谢谢！😄😆

**Comment by l-i-git** [comment]
我也是。点进视频有概率没有声音，暂停再播放也一样，但切换画质以后一般就有了。可能是视频是flv格式的问题？

**Comment by VillagerTom** [comment]
由于题主长时间未补充更多信息，关闭此议题。
