### ISSUE TITLE
主页同时长按多个视频时出现bug

### ISSUE THREAD

**Issue by KingRootwang** [orz12/PiliPalaX#144]
### 问题描述
主页同时长按多个视频后，无法关闭除第一个打开以外的封面

### 复现步骤
主页同时长按多个视频

### 预期行为
所有弹出的封面可关闭

### 错误日志

```
1.0.22-beta.5+167
```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by VillagerTom** [comment]
与#132重复
