### ISSUE TITLE
[FR] 播放页增加进入竖屏模式的功能

### ISSUE THREAD

**Issue by indefinabl** [orz12/PiliPalaX#149]
### 功能描述
希望可以上滑不进入全屏，而是进入竖屏模式

### 目标
播放页已经有全屏按钮了，上滑进入全屏和全屏按钮重复，但是没办法偶尔强制进入竖屏
### 解决方案
添加一个功能按钮，可以设置上滑进入竖屏，或者可以增加一个按钮可以更改全屏按钮为进入竖屏模式按钮

### 其他
可以参考哔哩哔哩官方应用播放页的竖屏按钮

**Comment by VillagerTom** [comment]
与#42 重复？

**Comment by indefinabl** [comment]
> 与#42 重复？

不是#42那种为了刷短视频，偶尔遇到某些视频想要居中观看，感觉更专注一点(背景黑色了)，就是单纯觉得那种界面看起来舒服，但是无法主动进入
