### ISSUE TITLE
[Bug] 评论循环出现

### ISSUE THREAD

**Issue by lingbopro** [orz12/PiliPalaX#175]
### 问题描述
如题，评论区的评论会循环出现

### 复现步骤
打开一个视频/动态（建议选择评论少的方便查看），滑动到底部，会发现之前的评论在这之后重复出现了，且顺序一样，循环次数不一定

### 预期行为
评论不应循环出现

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

APP: `1.0.22-beta.7+169`  
系统: `HarmonyOS 2 (Android 10)`  
设备: `HUAWEI Mate 20 Pro`  

### 相关信息
复现录屏：

https://github.com/user-attachments/assets/6408f3f3-071d-42d8-8b2b-9ecae01c3acb

**Comment by orz12** [comment]
已更新
