### ISSUE TITLE
[Bug] 切换页面后视频声音消失

### ISSUE THREAD

**Issue by ku12138** [orz12/PiliPalaX#181]
### 问题描述
请提供一个清晰而简明的问题描述。
切换页面后视频声音消失
### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by orz12** [comment]
你啥也不写我也没看懂

**Comment by VillagerTom** [comment]
> ### 问题描述
> 请提供一个清晰而简明的问题描述。
> **切换页面后视频声音消失**

🌿，内容搁这儿呢

**Comment by VillagerTom** [comment]
请补充具体复现步骤、设备系统/型号、APP版本号、视频BV号（如果必要）等信息。

**Comment by VillagerTom** [comment]
3个月未提供更多信息，此issue关闭。
