### ISSUE TITLE
[Bug] 播放视频时若弹幕透明度不为100%则会卡顿

### ISSUE THREAD

**Issue by imzoet** [orz12/PiliPalaX#188]
### 问题描述
播放视频时若开启弹幕，并且将透明度设置为非100%则会卡顿，即使播放720P也会卡顿，间歇性卡顿0.5s左右，关闭弹幕或者将透明度设置为100%播放后则正常不卡顿，原版APP亦有该BUG

### 系统信息
OS：Android 14，APP：最新版

**Comment by VillagerTom** [comment]
请提供更多信息如手机品牌型号、ROM型号等；APP版本号提供具体版本数字。

**Comment by imzoet** [comment]
更新了最新beta版，待我多测试下

**Comment by imzoet** [comment]
基于1.0.22-beta.8+170测试后未出现此问题

**Comment by imzoet** [comment]
基于1.0.22-beta.8+170测试后未出现此问题
