### ISSUE TITLE
[Bug] 更新最新版后字体变细

### ISSUE THREAD

**Issue by anjinga** [orz12/PiliPalaX#190]
### 问题描述
更新最新beta版后字体变细，看起来很不协调

### 复现步骤
打开app就能看到

### 预期行为
希望字体恢复到以前的粗体

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by orz12** [comment]
这项不同手机和字体不一样 比如我澎湃的默认字体有一部分就会变粗 是升级flutter引起的 暂时没有排查原因 目前优先解决升级后出现的bug

**Comment by xuangeyouneihan** [comment]
要不增加一个调节字重的选项？1.0.22-beta9的粗体我有点不习惯😂

**Comment by VillagerTom** [comment]
是ColorOS吗？

**Comment by orz12** [comment]
> 要不增加一个调节字重的选项？1.0.22-beta9的粗体我有点不习惯😂

目前计划继续升级flutter到pre版解决字重问题，并回调之前的字重设置

**Comment by VillagerTom** [comment]
关联issue：flutter/flutter/issues/154166
