### ISSUE TITLE
[Bug] 没有媒体通知

### ISSUE THREAD

**Issue by kanmurimori** [orz12/PiliPalaX#196]
![Screenshot_20240822151741](https://github.com/user-attachments/assets/052c7857-d36a-4928-8797-d5f46253f2d0)

顺带鞭一下 #183 。

**Comment by VillagerTom** [comment]
手机系统是什么？

**Comment by kanmurimori** [comment]
> 手机品牌/系统是什么？

m10u/Matrixx

**Comment by VillagerTom** [comment]
> > 手机品牌/系统是什么？
> 
> mi10u/Matrixx10(Android14)

类原生？

**Comment by kanmurimori** [comment]
> > > 手机品牌/系统是什么？
> > 
> > 
> > mi10u/Matrixx10(Android14)
> 
> 类原生？

嗯嗯

**Comment by orz12** [comment]
测一下新版

**Comment by kanmurimori** [comment]
> 测一下新版

通知是ok了可以关了
