### ISSUE TITLE
[Bug] ios16关于亮度记忆的问题

### ISSUE THREAD

**Issue by junevin1** [orz12/PiliPalaX#199]
### 问题描述
这个问题出在播放页面，在播放页面如果走到很亮或很暗的地方，等屏幕亮度变化之后返回主页，主页过一秒即会把亮度调整到之前的程度。并且之后系统的自动亮度失效，需要关闭屏幕才能恢复。（亮度记忆这个开关不起作用，开和关都是一样）

### 复现步骤
在播放页面如果走到很亮或很暗的地方，等屏幕亮度变化之后拉下系统通知或系统控制，你会发现亮度会返回之前的程度。

### 预期行为
希望关掉这个所谓的亮度记忆的功能。

**Comment by orz12** [comment]
新版去掉了 可以尝试一下
