### ISSUE TITLE
[Bug] 消息里别人的回复，不能跳转到指定的视频地址

### ISSUE THREAD

**Issue by yubanmayi** [orz12/PiliPalaX#201]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by orz12** [comment]
细节写一下

**Comment by lingbopro** [comment]
可能与 #176 是同一问题

**Comment by VillagerTom** [comment]
虽然不明白具体诉求是什么，但你可以看看新版1.1.0是否修复了你的问题。
