### ISSUE TITLE
[FR] 显示被b站隐藏的二级评论

### ISSUE THREAD

**Issue by cgykcftyi** [orz12/PiliPalaX#216]
### 功能描述
在评论界面，有些评论内有二级评论，但是被b站隐藏，但点击这些评论，它的二级评论依旧会展示，所以有没有可能做到直接在评论区看到这些二级评论。被隐藏的评论：
![Screenshot_20240829_154005.jpg](https://github.com/user-attachments/assets/f398939d-5c76-4f6d-817e-b63b170e0651)
![Screenshot_20240829_154108.jpg](https://github.com/user-attachments/assets/8596b9e4-dd9f-47d7-a245-96cbb05c9542)

### 目标
显示隐藏的二级评论

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by VillagerTom** [comment]
![Screenshot_2024-09-06-22-55-25-87_4c43f507ea86d7da90f806734e5ff8f2.jpg](https://github.com/user-attachments/assets/e4929449-c3d9-4809-801e-ce76a58a8f0e)

我这里是正常的啊

**Comment by cgykcftyi** [comment]
我的是有的评论底下不显示有子评论（就是底下不会显示有几个回复），但点一下评论进去之后会看到子评论（也就是楼），这应该是b站的系统检测到关键词了，或者说的人的隐藏分高了。不知有没有解决办法

**Comment by cgykcftyi** [comment]
比如视频BV1FzeneqE8p，你点进去一个叫原来你也听后朋的评论，就复现了，或者在玩政治梗的视频底下多点那些赞高没评论的，大概率就是被b站隐藏了

**Comment by cgykcftyi** [comment]
> ![Screenshot_2024-09-06-22-55-25-87_4c43f507ea86d7da90f806734e5ff8f2.jpg](https://private-user-images.githubusercontent.com/89803422/365210347-e4929449-c3d9-4809-801e-ce76a58a8f0e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzY2NjMsIm5iZiI6MTcyNTYzNjM2MywicGF0aCI6Ii84OTgwMzQyMi8zNjUyMTAzNDctZTQ5Mjk0NDktYzNkOS00ODA5LTgwMWUtY2U3NmE1OGE4ZjBlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE1MjYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYjBkZDQ1ZGQ5YThjNTQzNmNlZjA2M2VhMGMwN2IzMGYzNTM2ZDFjZjQ0ZGRjYzc2YTFkNzRhMGVjOGM1YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E1y-cv2z1li9ds4nFPd8X29n35JaubFamlwrXxEZvYM)
> 
> 我这里是正常的啊
比如视频BV1FzeneqE8p，你点进去一个叫原来你也听后朋的评论，就复现了，或者在玩政治梗的视频底下多点那些赞高没评论的，大概率就是被b站隐藏了

**Comment by VillagerTom** [comment]
> 我的是有的评论底下不显示有子评论（就是底下不会显示有几个回复），但点一下评论进去之后会看到子评论（也就是楼），这应该是b站的系统检测到关键词了，或者说的人的隐藏分高了。不知有没有解决办法

还能复现吗？发个BV号我看看我这里怎么样

**Comment by cgykcftyi** [comment]
> > 我的是有的评论底下不显示有子评论（就是底下不会显示有几个回复），但点一下评论进去之后会看到子评论（也就是楼），这应该是b站的系统检测到关键词了，或者说的人的隐藏分高了。不知有没有解决办法
> 
> 还能复现吗？发个BV号我看看我这里怎么样

BV1FzeneqE8p

**Comment by cgykcftyi** [comment]
> > 我的是有的评论底下不显示有子评论（就是底下不会显示有几个回复），但点一下评论进去之后会看到子评论（也就是楼），这应该是b站的系统检测到关键词了，或者说的人的隐藏分高了。不知有没有解决办法
> 
> 还能复现吗？发个BV号我看看我这里怎么样

原来你也听后朋的评论，稍微翻翻就找到了

**Comment by VillagerTom** [comment]
> > > 我的是有的评论底下不显示有子评论（就是底下不会显示有几个回复），但点一下评论进去之后会看到子评论（也就是楼），这应该是b站的系统检测到关键词了，或者说的人的隐藏分高了。不知有没有解决办法
> > 
> > 还能复现吗？发个BV号我看看我这里怎么样
> 
> 原来你也听后朋的评论，稍微翻翻就找到了

没找到这条
（看猫头鹰也不是后朋啊（

**Comment by cgykcftyi** [comment]
> > > > 我的是有的评论底下不显示有子评论（就是底下不会显示有几个回复），但点一下评论进去之后会看到子评论（也就是楼），这应该是b站的系统检测到关键词了，或者说的人的隐藏分高了。不知有没有解决办法
> > > 
> > > 
> > > 还能复现吗？发个BV号我看看我这里怎么样
> > 
> > 
> > 原来你也听后朋的评论，稍微翻翻就找到了
> 
> 没找到这条 （看猫头鹰也不是后朋啊（

![Screenshot_20240906_234959_com orz12 PiliPalaX](https://github.com/user-attachments/assets/9c4f368e-6646-4d90-bc93-238d734d4dc4)
![Screenshot_20240906_234959_com orz12 PiliPalaX](https://github.com/user-attachments/assets/1c1ee53d-95cd-4100-9a02-431370591e12)

**Comment by cgykcftyi** [comment]
![Screenshot_20240906_234953_com orz12 PiliPalaX](https://github.com/user-attachments/assets/a1724c42-65f1-471a-a32a-7196330ab0e3)

**Comment by VillagerTom** [comment]
我猜逻辑是当回复数≤1时不显示“共x条回复”，然后又碰到回复被折叠，直接什么都不显示了。

**Comment by cgykcftyi** [comment]
> 我猜逻辑是当回复数≤1时不显示“共x条回复”，然后又碰到回复被折叠，直接什么都不显示了。

![Screenshot_20240907_065605_com.orz12.PiliPalaX.jpg](https://github.com/user-attachments/assets/c871829b-0993-40a9-a523-1997048904bf)

![Screenshot_20240907_065619_com.orz12.PiliPalaX.jpg](https://github.com/user-attachments/assets/0e40839f-882f-4b0a-9ac5-7a7aff93332f)

这底下有两个评论，但还是被隐藏了

**Comment by cgykcftyi** [comment]
> > 我猜逻辑是当回复数≤1时不显示“共x条回复”，然后又碰到回复被折叠，直接什么都不显示了。
> 
> ![Screenshot_20240907_065605_com.orz12.PiliPalaX.jpg](https://github.com/user-attachments/assets/c871829b-0993-40a9-a523-1997048904bf)
> 
> ![Screenshot_20240907_065619_com.orz12.PiliPalaX.jpg](https://github.com/user-attachments/assets/0e40839f-882f-4b0a-9ac5-7a7aff93332f)
> 
> 这底下有两个评论，但还是被隐藏了

BV1a1pGegEUQ

**Comment by orz12** [comment]
这个共x条回复是后端返回的，不是由前端统计显示的
![image](https://github.com/user-attachments/assets/f49c36d9-7aec-40f1-8dde-8adf124ff685)

> BV1a1pGegEUQ
这边我正常显示出了两条回复（无论是否登录）

> 比如视频BV1FzeneqE8p，你点进去一个叫原来你也听后朋的评论，就复现了，或者在玩政治梗的视频底下多点那些赞高没评论的，大概率就是被b站隐藏了
这个复现出来了，该接口返回内容如图所示：
![image](https://github.com/user-attachments/assets/52f4e764-db53-4936-a883-521a503b5eb7)
可以观察到，"replies": []说明没有返回外显的评论回复结果（返回了一个空列表），但在reply_control中，则传递了“共1条评论”。

下个版本针对这种replies为空但sub_reply_entry_text存在的情况，会额外特判一下，也就是说仅显示一行【共1条回复】，但只能点进去才能看到回复内容。

为什么不专门再请求到子回复再外显？我认为这样太累赘了，实现上，状态管理会变复杂；界面上，列表也会跳动影响体验；从b站角度而言，也背离了隐藏的初衷。但为了用户的知情权，改为外显条数（毕竟信息是有的），当你看到这样的提示时可以手动点进去。

欢迎在下个版本参与测试。

**Comment by cgykcftyi** [comment]
> 这个共x条回复是后端返回的，不是由前端统计显示的
> ![image](https://github.com/user-attachments/assets/f49c36d9-7aec-40f1-8dde-8adf124ff685)
> 
> > BV1a1pGegEUQ
> 
> 这边我正常显示出了两条回复（无论是否登录）
> 
> > 比如视频BV1FzeneqE8p，你点进去一个叫原来你也听后朋的评论，就复现了，或者在玩政治梗的视频底下多点那些赞高没评论的，大概率就是被b站隐藏了
> 
> 这个复现出来了，该接口返回内容如图所示：
> ![image](https://github.com/user-attachments/assets/52f4e764-db53-4936-a883-521a503b5eb7)
> 可以观察到，"replies": []说明没有返回外显的评论回复结果（返回了一个空列表），但在reply_control中，则传递了“共1条评论”。
> 
> 下个版本针对这种replies为空但sub_reply_entry_text存在的情况，会额外特判一下，也就是说仅显示一行【共1条回复】，但只能点进去才能看到回复内容。
> 
> 为什么不专门再请求到子回复再外显？我认为这样太累赘了，实现上，状态管理会变复杂；界面上，列表也会跳动影响体验；从b站角度而言，也背离了隐藏的初衷。但为了用户的知情权，改为外显条数（毕竟信息是有的），当你看到这样的提示时可以手动点进去。
> 
> 欢迎在下个版本参与测试。

OK，非常感谢开发大大的解答，Let's make bilibili great again!

**Comment by VillagerTom** [comment]
@orz12 这个bug的修复发在release里了吗？如果发了可以关闭这个issue。
