### ISSUE TITLE
[FR] 能在指定用户主页进行搜索时精确搜索到包含该关键词的动态。

### ISSUE THREAD

**Issue by ahbksdmz** [orz12/PiliPalaX#217]
### 功能描述
能在指定用户主页进行搜索时精确搜索到包含该关键词的动态。

### 目标
根据关键词准确的搜索某个用户的动态

### 其他
哔哩哔哩官方app中的用户页面的搜索，但需要提高搜索精度。

**Comment by orz12** [comment]
除非你能在官方找到符合你需求的搜索 不然这里做不了

**Comment by orz12** [comment]
> 哔哩哔哩的安卓客户端进入up主页后可以用关键词搜索动态，但精度存在问题，可以本地过滤一下吗？。例如我在up主页搜索带有“优香”的动态，但是部分搜索到的动态包含是“遥香”、“芹香”、“优秀的”……，关键词不完全匹配，缺少我要的带有“优香”的动态，可以在本地对其进行过滤，隐藏只带部分搜索关键词的动态吗？

设想很好，但是这种情况下应该是已经模糊匹配了，本地过滤基本上会导致所有的结果都消失，没有什么意义。如果官方有精确匹配的搜索接口才是解决方法
