### ISSUE TITLE
[Bug] 弹幕速度受系统动画速度影响

### ISSUE THREAD

**Issue by ghost** [orz12/PiliPalaX#223]
### 问题描述
弹幕速度受系统动画速度影响，导致弹幕移动速度过快。

### 复现步骤
在开发者选项中调整动画缩放为0x。

### 预期行为
弹幕速度不受系统动画速度影响

### 错误日志
无。
Android 14
PiliPalaX 版本 1.0.22-beta.9
arm64-v8a

### 相关信息
暂无

**Comment by VillagerTom** [comment]
@orz12 要不要给@xiaoyaocz 佬写个issue？

**Comment by orz12** [comment]
目前我查到的资料显示flutter好像没有机制可以忽略或者屏蔽该设置，所以我目前在弹幕时长里提供了最高256秒的选项，在我的手机上可以对抗0x过渡动画的设置（因为系统并不是真的改成0，只是乘一个比较小的系数，大概是0.01这种量级）
如果有找到更标准或者符合规范的做法欢迎提出
