### ISSUE TITLE
[FR] CDN 测速

### ISSUE THREAD

**Issue by xuangeyouneihan** [orz12/PiliPalaX#228]
### 功能描述
在 CDN 设置中添加一个测速按钮，点进去将测试所有 CDN 的速度和延迟并排名

### 目标
允许用户了解并选择所在地区最快的 CDN

### 解决方案
我不知道

### 其他
哔哩漫游已实现该功能

**Comment by VillagerTom** [comment]
你可以点Edit编辑issue内容...

**Comment by xuangeyouneihan** [comment]
@VillagerTom 我感觉这个没有 duplicate 啊，这个和 #229 内容不一样的，请求重新

**Comment by xuangeyouneihan** [comment]
@VillagerTom 我感觉这个没有 duplicate 啊，这个和 #229 内容不一样的，请求重新 open

**Comment by VillagerTom** [comment]
从功能上两者是一样的，只不过在UI上加个按键用来手动测速
