### ISSUE TITLE
[Bug] 在平板上使用时无法列出所有收藏夹 

### ISSUE THREAD

**Issue by achee2019** [orz12/PiliPalaX#230]
### 问题描述

平板上列出收藏夹的界面无法下滑，导致不能列出所有收藏夹。

### 复现步骤

在平板上安装最新版PiliPalaX：[1.0.22-beta.9+171]或[1.0.22+162]。登录，查看收藏夹界面只显示2列10行共计20个收藏夹，无法查看剩余收藏夹。

### 预期行为

列出收藏夹的界面可以下滑显示所有的收藏夹。

### 错误日志

```
APP版本：[1.0.22-beta.9+171]和[1.0.22+162]
设备：小米平板4 Mi Pad 4
系统：魔趣 MK100.0
硬件信息：骁龙660, 4GB RAM, 1920 x 1200
```

### 相关信息

平板安装Pilipala或手机安装PilipalaX时都没有出现以上问题，考虑到这两种情况都是收藏夹单列展示，是不是平板上的PilipalaX在双列展示时有显示Bug？

#### 截图
显示有27个文件夹
![Screenshot_20240906-012824_PiliPalaX](https://github.com/user-attachments/assets/12aaf134-3082-471b-8b2f-446f79807eaf)

实际只能看见20个，无法滑动或翻页
![Screenshot_20240906-012857_PiliPalaX](https://github.com/user-attachments/assets/25ccefc2-093a-42b3-8e22-d808a92551d3)

**Comment by orz12** [comment]
展示内容过多导致的 可以看一下新版有没有修
