### ISSUE TITLE
[Bug] 观看竖屏视频，横屏适配出错

### ISSUE THREAD

**Issue by yezechuandl** [orz12/PiliPalaX#232]
### 问题描述
平板开启横屏适配后，全屏观看竖屏的视频，软件屏幕占比出错，退出全屏依然无法改变。

### 复现步骤
找一个竖屏的视频，进入全屏，屏占比改变。

### 预期行为
留两个大黑边也好，希望全屏能保持正常的屏幕占比。

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```
app版本:1.0.22-beta.10+127
系统版本:安卓12
设备型号:Lenovo TB-J606F
```

### 相关信息

https://github.com/user-attachments/assets/17ef09a0-d6da-47ee-ac29-2859c9e938cd

**Comment by orz12** [comment]
是新版才出现的还是之前就有遇到？

**Comment by orz12** [comment]
你设置过全屏方式吗？有没有选择【不改变当前方向】或者【强制按重力旋转】之类的？

**Comment by yezechuandl** [comment]
> 是新版才出现的还是之前就有遇到？

之前的版本就有了，看没人提问题，就自己来了。

**Comment by yezechuandl** [comment]
> 你设置过全屏方式吗？有没有选择【不改变当前方向】或者【强制按重力旋转】之类的？

全屏方式没动过，也没看见有这个好像。。。就是方便不全屏看竖屏视屏开了个竖屏扩大展示，没开是一样的。

**Comment by orz12** [comment]
> > 你设置过全屏方式吗？有没有选择【不改变当前方向】或者【强制按重力旋转】之类的？
> 
> 全屏方式没动过，也没看见有这个好像。。。就是方便不全屏看竖屏视频开了个竖屏扩大展示，没开是一样的。

在播放器设置里 先改了再说

**Comment by yezechuandl** [comment]
> > > 你设置过全屏方式吗？有没有选择【不改变当前方向】或者【强制按重力旋转】之类的？
> > 
> > 全屏方式没动过，也没看见有这个好像。。。就是方便不全屏看竖屏视频开了个竖屏扩大展示，没开是一样的。
> 
> 在播放器设置里 先改了再说

改成[不改变当前方向]没问题了，一直没注意到🙃
