### ISSUE TITLE
[FR] 无痕模式支持大会员分辨率及评论ip属地展示

### ISSUE THREAD

**Issue by My-Responsitories** [orz12/PiliPalaX#236]
### 功能描述
添加开关，允许`/x/player/wbi/playurl`, `/x/v2/reply/main`(`/x/v2/reply/wbi/main`), `/x/v2/reply/reply`携带cookie进行请求. 只有视频接口携带cookie进行请求的话并不会记录播放历史, 评论接口仅在携带cookie时可获取ip属地

### 目标
无痕模式支持仅大会员及评论ip属地展示

### 解决方案
添加开关，允许`/x/player/wbi/playurl`, `/x/v2/reply/main`(`/x/v2/reply/wbi/main`), `/x/v2/reply/reply`携带cookie进行请求

**Comment by orz12** [comment]
无痕模式的目的是对抗b站推荐算法 不是用来暂停播放历史记录的 需要暂停的话 在历史记录右上角暂停记录即可
