### ISSUE TITLE
[Bug] 视频播放错误

### ISSUE THREAD

**Issue by GD2021** [orz12/PiliPalaX#238]
### 问题描述
在我的Pixel7 pro上使用，所有的视频播放错误

### 预期行为
请问如何解决？

### 相关信息
https://github.com/GD2021/picx-images-hosting/raw/master/Github反馈/photo_2024-09-13_08-43-33.3rb6l8qhlw.webp
https://github.com/GD2021/picx-images-hosting/raw/master/Github反馈/photo_2024-09-13_08-35-32.2krvcn1l0j.webp

**Comment by VillagerTom** [comment]
最新版提供了切换CDN的功能，是否还有相同错误？

**Comment by VillagerTom** [comment]
因长时间未提供后续反馈，关闭此issue。
