### ISSUE TITLE
[FR] 简介显示在标题下方

### ISSUE THREAD

**Issue by huajideshutiao** [orz12/PiliPalaX#245]
### 功能描述
现在需要点击标题才能显示完整的标题和bv号、简介等内容，可以改成像官方那样直接显示

### 目标
大部分标题和简介都挺短，感觉没必要再单独点一次

**Comment by VillagerTom** [comment]
我刷到的大部分视频简介都很长。

鉴定为看短视频看多了

**Comment by huajideshutiao** [comment]
> 我刷到的大部分视频简介都很长。
> 
> 鉴定为看短视频看多了

不至于吧，我刷的基本是2min左右的视频，虽然不太长
不过很多视频倒是不写简介。
