### ISSUE TITLE
[FR] 接入 B站空降助手 API

### ISSUE THREAD

**Issue by ybhgl** [orz12/PiliPalaX#246]
### 功能描述
[B站空降助手](https://github.com/hanydd/BilibiliSponsorBlock) 是一个类似 [SponsorBlock](https://github.com/ajayyy/SponsorBlock) 的插件，可以用来跳过B站视频中的恰饭片段，可以显著提升观看体验

### 目标
接入API，实现自动跳过恰饭片段、手动提交自己标注的片段等功能

### 解决方案
https://wiki.sponsor.ajay.app/w/API_Docs

### 其他
无

**Comment by orz12** [comment]
我个人不会提供这类有破解嫌疑的功能 可以转用其他的版本
