### ISSUE TITLE
[Bug] 软件和浏览器 在一起了

### ISSUE THREAD

**Issue by Vuilevis** [orz12/PiliPalaX#252]
https://github.com/user-attachments/assets/adc5c5ad-da89-4d68-9125-08f35345096d

软件和浏览器 在一起了

**Comment by VillagerTom** [comment]
坏(#｀皿′)我不同意这门婚事

**Comment by lingbopro** [comment]
这是浏览器的事吧

Chrome，Edge 之类的都有这种功能，嵌入在其他应用界面上的不完整浏览器界面

**Comment by orz12** [comment]
这不属于本APP的bug

**Comment by VillagerTom** [comment]
可能与手机系统有关？我的3台手机从PiliPalaX打开Via浏览器均没有此bug。或许你可以去Via那边反馈一下？
