### ISSUE TITLE
[FR] 三连

### ISSUE THREAD

**Issue by belugaQAQ** [orz12/PiliPalaX#260]
### 功能描述
请提供对所请求功能的清晰描述。
一键三连
### 目标
请描述你希望通过这个功能实现的目标。
一键三连
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。
无
### 其他
请提供已实现该功能或类似功能的应用
BBLL

**Comment by VillagerTom** [comment]
有一键三连功能，只是目前没有动画。

**Comment by belugaQAQ** [comment]
那怎么三连呢？

**Comment by nightgpt** [comment]
> 那怎么三连呢？

一样的，还是长按点赞按钮
