### ISSUE TITLE
[Bug] 个人主页无法显示信息

### ISSUE THREAD

**Issue by xuangeyouneihan** [orz12/PiliPalaX#274]
### 问题描述
见“相关信息”那里的录屏，也许和网络环境有关系，也许和风控有关系

### 复现步骤
点进任意用户的主页

### 预期行为
个人主页正常显示

### 错误日志
无

### 相关信息
[video_compressed.mp4](https://github.com/user-attachments/assets/84f86b8a-142d-4ee1-a566-0b76b5ad1368)

**Comment by zihu12** [comment]
似乎`/x/space/wbi/acc/info`的风控处理出了问题
```JSON
{
  "code": -352,
  "message": "风控校验失败",
  "ttl": 1,
  "data": {
    "v_voucher": "voucher_***"
  }
}
```
可能与[这个新参数](https://github.com/SocialSisterYi/bilibili-API-collect/issues/1107)[有关](https://github.com/SocialSisterYi/bilibili-API-collect/issues/868#issuecomment-2408470885)？

**Comment by lingbopro** [comment]
me too，我也这样

https://github.com/user-attachments/assets/afa62a0f-1866-4b09-9b04-5bfc6b4d408a

**Comment by shouge** [comment]
我也发现个人信息 在上周会返回风控校验失败!

**Comment by jinyinghua** [comment]
我也有这个问题，有什么解决方法吗

**Comment by VillagerTom** [comment]
35b502ff740d72971d88537b6146caed92b7a449

**Comment by lingbopro** [comment]
> 35b502ff740d72971d88537b6146caed92b7a449


静等新版本ing...

**Comment by VillagerTom** [comment]
新版本1.1.0已发布。

**Comment by lingbopro** [comment]
> 新版本1.1.0已发布。

:)
