### ISSUE TITLE
[Bug] 自签安装失败

### ISSUE THREAD

**Issue by PIE-xu** [orz12/PiliPalaX#276]
### 问题描述
SideStore签名工具个人证书签名失败

### 复现步骤
1、连接Wi-Fi和VPN
2、打开自签工具
3、签名&安装

### 预期行为
成功安装

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```
安装报错如下：
/Users/runner/Library/Developer/Xcode/DerivedData/AltStore-dunvejkuqerofjghtqolpzgexuyv/SourcePackages/checkouts/AltSign/Sources/ldid/../ldid-core/ldid.cpp(1368): _assert(): end >= size - 0x10

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by zengjiapei3000** [comment]
这里有类似的问题
https://github.com/guozhigq/pilipala/issues/73
