### ISSUE TITLE
[Bug] 平板模式竖屏视频bug

### ISSUE THREAD

**Issue by PangYanze** [orz12/PiliPalaX#279]
### 问题描述
平板兼容模式下，动态竖屏视频下，点击全屏，显示异常；退出后横屏适配异常

### 相关信息
![Screenshot_2024-10-19-15-03-40-798_com orz12 PiliPalaX](https://github.com/user-attachments/assets/b27f1f88-5af2-4536-83f1-013f97c49d7f)

![Screenshot_2024-10-19-15-03-35-943_com orz12 PiliPalaX](https://github.com/user-attachments/assets/e1f84199-4fd4-4a0d-b233-8741a167a2d2)
![Screenshot_2024-10-19-15-03-32-399_com orz12 PiliPalaX](https://github.com/user-attachments/assets/4fcdd295-ba78-401d-bd37-bbeee5dbf9b1)

**Comment by VillagerTom** [comment]
请提供设备型号、系统版本等信息。

**Comment by orz12** [comment]
你没有设置正确的全屏方向，另外你的版本也旧了
