### ISSUE TITLE
[Bug] 为什么我不登录我就不能看他人的投稿？ 

### ISSUE THREAD

**Issue by SuicideMouse2023** [orz12/PiliPalaX#287]
### 问题描述
为什么我不登录我就不能看他人的投稿？
以前都可以

### 复现步骤
点开某人的主页，再点Ta的投稿

### 预期行为
可以不登录就可以看他人的投稿

### 错误日志
手机:Redmi 9a
手机型号:M2006C3LC
APP版本:1.0.22-Beta.12

```

```

### 相关信息
![Screenshot_2024-10-25-14-30-07-150_com orz12 PiliPalaX](https://github.com/user-attachments/assets/58460eef-b540-4c39-9bb9-dbcf37f74adc)

**Comment by VillagerTom** [comment]
与 #275 重复
