### ISSUE TITLE
[FR] Linux版本

### ISSUE THREAD

**Issue by AifaiXiu** [orz12/PiliPalaX#289]
### 功能描述
有大佬可以打包一下linux版本的安装包么

**Comment by nlsdt** [comment]
> ### 功能描述
> 有大佬可以打包一下linux版本的安装包么
> 
> 

这是给手机的软件，为什么要linux安装包？何况目前flutter在Linux的实现目前也并不完善。

**Comment by ajdgsu** [comment]
> ### 功能描述
> 
> 有大佬可以打包一下linux版本的安装包么

有人做了一个，不过没开源而且只发了网盘链接
不确定原帖是在哪个平台上发的，我是在酷安上见到的
https://www.coolapk.com/feed/59905578

**Comment by VillagerTom** [comment]
![IMG_20241102_121744.JPG](https://github.com/user-attachments/assets/27a0d1c3-1bbc-4e15-b0d6-73bc83971ad1)

截自官方QQ群，其中管理员为PiliPalaX开发者。

**Comment by AifaiXiu** [comment]
@ajdgsu 这个就是我自己去打包的那个，编译确实过了，基本能用，但是有个我不能接受的bug,不能登陆还好，主要是有些视频点进去黑屏，其实我感觉这个应该好解决的，指定解码方式或者直接写死默认播放器，或者内嵌一个进去，也不是很难的事情，官方说编译过不了需要注释，但是我当时archlinux确实编译过了，打包了一个版本，至于登陆的话可以用web端的实现啊，
@VillagerTom
