### ISSUE TITLE
[FR] 关于视频内音量与亮度上下调节功能

### ISSUE THREAD

**Issue by pptext** [orz12/PiliPalaX#299]
### 功能描述
视频全屏后的音量与亮度上下调节功能，希望可以更灵敏，现版本的调节，从屏幕最底下拉到最上面也只增加了30%，希望调成滑动一次就能从0调到100，像官方客户端一样

**Comment by VillagerTom** [comment]
新版1.1.0是否已满足需求？

**Comment by orz12** [comment]
亮度没有必要调得太灵敏 音量是比较灵敏的 目前可以再测试一下新的版本
