### ISSUE TITLE
[Bug] 点击评论区用户主页，不显示动态

### ISSUE THREAD

**Issue by XicunKing** [orz12/PiliPalaX#301]
### 问题描述
从视频评论区的用户头像点进去，显示主页空，不显示动态页。

### 复现步骤
打开视频，打开评论区，点击评论用户

### 预期行为
出现用户主页动态

### 错误日志
![Screenshot_20241109_161519](https://github.com/user-attachments/assets/4d97d197-1929-4e45-bdf6-a30f32d9caf1)
![Screenshot_20241109_161407_com orz12 PiliPalaX](https://github.com/user-attachments/assets/2221131d-0470-49b7-83c1-12397c900fc5)

最新版本
```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by XicunKing** [comment]
版本号截图
![Screenshot_20241109_161937_com orz12 PiliPalaX](https://github.com/user-attachments/assets/e3b324fc-84cf-4b1d-a3c2-df948a390c16)

**Comment by VillagerTom** [comment]
与#274 或#283 重复
