### ISSUE TITLE
[Bug] beta版本返回键会直接退出应用

### ISSUE THREAD

**Issue by 2103894869** [orz12/PiliPalaX#302]
### 问题描述
请提供一个清晰而简明的问题描述。
在beta版本下，任何界面使用系统导航返回键会直接退出应用
### 复现步骤
请提供复现该问题所需的具体步骤。
百分百复现
### 预期行为
请描述你期望的正确行为或结果。
退回上级页面
### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。
PiliPalaX错误日志
********************
------- 设备信息 -------
id: UKQ1.230804.001
board: shennong
bootloader: unknown
brand: Xiaomi
device: shennong
display: UKQ1.230804.001 release-keys
fingerprint: Xiaomi/shennong/shennong:14/UKQ1.230804.001/V816.0.50.0.UNBCNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-324144-pz8m7-47mtr-6xq4c
isPhysicalDevice: true
manufacturer: Xiaomi
model: 23116PN5BC
product: shennong
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V816.0.50.0.UNBCNXM
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-09-01
------- 应用信息 -------
environment: release
version: 1.0.22-beta.12
appName: PiliPalaX
buildNumber: 1743
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
type 'Null' is not a subtype of type 'Map<String, dynamic>'
------- 错误堆栈 -------
#0      Utils.checkUpdate (package:PiliPalaX/utils/utils.dart:324)
<asynchronous suspension>
------- CUSTOM INFO -------
```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by VillagerTom** [comment]
是否使用beta版小米桌面？最新版已通过屏蔽预测性返回规避此bug。
