### ISSUE TITLE
[Bug] 个人空间信息不显示、显示有误

### ISSUE THREAD

**Issue by FlootingDream** [orz12/PiliPalaX#309]
### 问题描述
点击up头像进入个人空间后，短暂展示个人信息，然后迅速消失
点击自己的头像，同样会触发

**Comment by FlootingDream** [comment]
展示视频：
https://github.com/user-attachments/assets/8699892c-fafa-4982-81fc-393b303f31ad

**Comment by VillagerTom** [comment]
与 #274 重复
