### ISSUE TITLE
[Bug] 登录闪退

### ISSUE THREAD

**Issue by 848128382** [orz12/PiliPalaX#313]
### 问题描述
一点登录就闪退

### 复现步骤
在tg下载安装，点进去输入账号密码，点登录按钮闪退

### 预期行为
希望修复

### 错误日志
无日志信息
app版本：1.0.22-beta12
手机：魅族21Pro
系统：安卓14  flyme11.2
```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by orz12** [comment]
试一下新版本
