### ISSUE TITLE
复制文字时手机振动

### ISSUE THREAD

**Issue by CreeperAWA** [orz12/PiliPalaX#315]
我也不清楚振动是否正常，是不是我的设备问题（HUAWEI Nova 5 Pro），不过我觉得这似乎太猛烈了，可以减轻或移除，如果是我的设备问题，请问可以给我提供一个解决方案吗，谢谢！

**Comment by VillagerTom** [comment]
复制文件是指？

**Comment by CreeperAWA** [comment]
> 复制文件是指？

文字，用手机打字没看清

**Comment by VillagerTom** [comment]
可以去其他设置->震动反馈关闭。

**Comment by CreeperAWA** [comment]
我看了一下 我本来就是关闭的
