### ISSUE TITLE
[FR] 动态页可否自动播放视频?

### ISSUE THREAD

**Issue by EyoZoi** [orz12/PiliPalaX#319]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by VillagerTom** [comment]
需求较小且会使路由管理变复杂，暂时不会实现。

**Comment by orz12** [comment]
暂不提供自动播放能力
