### ISSUE TITLE
[FR] 提一个可能有点遥远的功能请求，能加一个成分检测器的功能吗

### ISSUE THREAD

**Issue by Perpetual-Memories** [orz12/PiliPalaX#320]
### 功能描述
B站评论区标注成分

### 目标
检测评论区用户成分

### 解决方案
在长按评论的菜单中提供检测当前用户成分的选项，在右下角提供检测当前评论区所有用户成分的按钮

### 其他
[（改）B站成分检测器](https://greasyfork.org/zh-CN/scripts/462288-%E6%94%B9-b%E7%AB%99%E6%88%90%E5%88%86%E6%A3%80%E6%B5%8B%E5%99%A8)

**Comment by VillagerTom** [comment]
不会添加（加剧）破坏社区环境的功能。
