### ISSUE TITLE
动画缺失【严重】

### ISSUE THREAD

**Issue by XHJXHJXHJXHJ** [orz12/PiliPalaX#321]
动画效果缺失 对比pilipala普通版大部分动画返回效果缺失
**影响用户体验**

**Comment by orz12** [comment]
个人能力有限，做不出精美的动画……你可以根据喜好选择使用的app

**Comment by XHJXHJXHJXHJ** [comment]
不过pilipala有的动画pilipalax没有-------- 原始邮件 --------发件人： orz12 ***@***.***>日期： 2024年12月23日周一 07:35收件人： orz12/PiliPalaX ***@***.***>抄送： 星河间v ***@***.***>, Author ***@***.***>主    题： Re: [orz12/PiliPalaX] 动画缺失【严重】 (Issue #321)
个人能力有限，做不出精美的动画……你可以根据喜好选择使用的app
