### ISSUE TITLE
[Bug] 不显示系统导航键

### ISSUE THREAD

**Issue by xfdyd** [orz12/PiliPalaX#335]
### 问题描述
打开这个视频：
https://www.bilibili.com/video/BV1M3yqYTEyW
全屏。单击。最下面空白，没有系统虚拟导航键。

### 错误日志
app175个人修改版、安卓13

### 相关信息
![_20241228_193901](https://github.com/user-attachments/assets/b156fb64-9f54-49ed-8d9a-6bc7550cf4a7)

**Comment by VillagerTom** [comment]
任何视频全屏状态都不会显示虚拟导航键。

**Comment by orz12** [comment]
符合预期

**Comment by xfdyd** [comment]
但是这个就显示：
https://www.bilibili.com/video/BV1Tr4y1s7NA
