### ISSUE TITLE
可以加个刷短视频的模式吗？

### ISSUE THREAD

**Issue by tao101400** [orz12/PiliPalaX#42]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by orz12** [comment]
不会提供该项功能，如有需求，推荐尝试使用b站谷歌版本。

**Comment by herexiong** [comment]
异端！（bushi

**Comment by xiefenchao-x** [comment]
那你用这个干嘛👿

**Comment by yiqifengba** [comment]
刷短视频不如直接用抖音，而且内容太差了，都什么王者、短小说、恶俗情节，很多还是抖音一键分发过来的，喂屎。
