### ISSUE TITLE
APP未备案导致被腾讯病毒库报毒

### ISSUE THREAD

**Issue by IanLee1024** [orz12/PiliPalaX#84]
![Screenshot_2024-05-20-14-54-30-362_com miui securitycenter](https://github.com/orz12/pilipala/assets/114343432/3fa6b8c2-dbd5-423a-bdc4-f2de420a0ea4)
被腾讯扫出来病毒了

**Comment by orz12** [comment]
你搜一下这个代号a.gray.BulimiaTGen.h是什么就知道了…本来就是个人开发者，这个app的性质也不适合申报，总不能交个《xxx业务许可证》，就随便了呗，反正开源的，要多少权限，有没有问题，代码想看就看…

**Comment by IanLee1024** [comment]
对不起，我先用百度没有搜到这个报毒的有效信息，于是就想着反馈一下，我并没质疑这个项目的意思，如果给你带来了不好的情绪，我诚恳地向你道歉。

**Comment by orz12** [comment]
哦哦没有没有 我其实很平和 没有生气啥的 这里没有表情包可用 让你误解了 这个报毒上上上个版本就有了 我是谷歌搜的 知乎或者CSDN也能找到 正常现象 很早就有人来问 没关系的

**Comment by VillagerTom** [comment]
详见此帖 https://hk.v2ex.com/t/1029920
