### ISSUE TITLE
支持关闭播放页截图键

### ISSUE THREAD

**Issue by wanzh5** [orz12/PiliPalaX#86]
比较容易误触，而且误触之后还要去把截图删掉，很麻烦。所以希望可以支持关闭截图键。

**Comment by orz12** [comment]
后续可能会做成一个悬浮小图片的形式确认，点击再保存，不知道实现难度如何。

**Comment by VillagerTom** [comment]
1.1.0已支持关闭。播放器设置->全屏时显示额外功能
