### ISSUE TITLE
不支持 120fps

### ISSUE THREAD

**Issue by tkkcc** [orz12/PiliPalaX#99]
使用一加ace2，该app不支持120fps，相比原版b站滑动和动画有卡顿感。这是 flutter 的限制吗，flutter  2024 年还不支持 120fps 吗。

![Screenshot_2024-06-13-01-37-30-40_4c43f507ea86d7da90f806734e5ff8f2](https://github.com/orz12/pilipala/assets/17373509/1bad21a7-8b3e-4a64-bff1-0282e3217f9e)
![Screenshot_2024-06-13-01-40-36-35_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/orz12/pilipala/assets/17373509/4c18c91f-9739-4b46-9103-cb2894c58cd3)

**Comment by orz12** [comment]
因为列表滑动需要专门进行性能优化，水平和精力有限暂时还没有做；目前显示60帧也有可能在外观设置-帧率设置中可调整（该功能只能向系统进行建议，没有决定权，最终效果也有差异）
